name: deploy-website

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    paths:
      site/**

  workflow_dispatch:


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    if: ${{ github.event.action }} == 'opened'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the site
      run: |
        sphinx-build site/ site/_build
        cp CNAME site/_build

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site/_build/
