name: test-build

# Only run this when a PR is made to main.
# It tests the build, but doesn't deploy it.
on:
  pull_request:
    branches: 
    - main
    paths:
      site/**

  workflow_dispatch:

# Try and see if we can build the website, but don't deploy it.
jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the site
      run: |
        sphinx-build site/ site/_build/
